{
    'name': "taz-package",
    'summary': """Ensemble de tous les package à installer pour Tasmane""",
    'description': """
    """,
    'author': "Aurélien Dumaine",
    'website': "https://www.dumaine.me",
    'license': 'LGPL-3',
    'category': 'Uncategorized',
    'version': '17.0',
    'depends': [
		'account_financial_report',
		'account_invoice_inter_company',
		'account_move_line_reconcile_manual',
		'agreement',
		'agreement_purchase',
		'agreement_sale',
		'base_view_inheritance_extension',
		'company_dependent_flag',
		'dashboard_global',
		'date_range',
		'event_registration_light',
		'l10n_fr_siret',
		'l10n_fr_siret_lookup',
		'many2many_tags_link_sit',
		'napta_connector',
		'project_accounting',
		'project_accounting_inter_company',
		'purchase_sale_inter_company',
		'report_label',
		'report_wkhtmltopdf_param',
		'report_xlsx',
		'server_action_mass_edit',
		'spreadsheet_dashboard_oca',
		'spreadsheet_dashboard_transverse',
		'spreadsheet_filters',
		'spreadsheet_oca',
		'ssq_login_as_user',
		'staffing',
		'taz-common',
		'web_chatter_position',
		'web_company_color',
		'web_widget_bokeh_chart',
		'web_widget_open_tab',
		'web_window_title',
    ],
    'data': [],
}

