from . import staffing
from . import project
from . import employee
from . import account_analytic_line
from . import hr_leave
from . import hr_job
from . import hr_contract
from . import employee_staffing_report
from . import res_company
