from . import project_stage
from . import project_group
from . import project
from . import res_partner
from . import project_outsourcing_link
from . import project_book
from . import account_move
from . import sale_order
from . import purchase_order
from . import project_accounting_closing
from . import analytic_account
from . import payment
